version: "3.9"

services:
    web:
        build:
            context: .
            dockerfile: ./docker/nginx.dockerfile
        volumes:
            - static_volume:/usr/src/app/staticfiles
        ports:
            - 80:80
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: ./docker/python.dockerfile
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./app:/code
            - static_volume:/usr/src/app/staticfiles
        expose:
            - 8000
        env_file:
            - ./app/.env
        depends_on:
            - db

    db:
        build:
            context: .
            dockerfile: ./docker/postgres.dockerfile
        volumes:
            - db_data:/var/lib/postgresql/data
        env_file:
            - ./db/.env

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - "8888:80"
        env_file:
            - ./db/.env

volumes:
    db_data:
    static_volume: